development:
  adapter: mysql2
  encoding: utf8
  database: impersona_development
  username: <%= ENV['mysql_user'] %>
  password: <%=ENV['mysql_password'] %>
  host: <%= ENV['mysql_host'] %>

test:
  adapter: mysql2
  encoding: utf8
  database: impersona_test
  username: travis
